server {
    listen 80;

    # Tier 1: Static frontend serve karo
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Reverse proxy: /api/ pe koi bhi request aaye to backend container ko forward karo
    # Ye wahi Nginx concept hai jo tu abhi seekh raha hai -- bas ab real use-case mein!
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
